apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - target:
      kind: Service
    patch: |-
        - op: replace
          path: /metadata/namespace
          value: staging
