apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hellosprint-staging
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: deployment
spec:
  destination:
    namespace: sprint-staging
    server: https://kubernetes.default.svc
  project: sprint-staging
  source:
    chart: sprint-flask-app
    repoURL: https://sprint-cloud.github.io/helm-charts
    targetRevision: "0.1"
    helm:
      values: |-
          image: 
            repository: ghcr.io/sprint-cloud/hello-sprint
            tag: 8a9ebf53b7c2a10068b30bd0c173d60a90733ca2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
