apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    networking.knative.dev/enableWildcardCert: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    networking.knative.dev/enableWildcardCert: "true"