apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-production
  namespace: argocd
spec:
  destinations:
  - server: https://kubernetes.default.svc
    namespace: production
  clusterResourceWhitelist:
  - group: 'serving.knative.dev'
    kind: 'Service'
  - group: argoproj.io/v1alpha1
    kind: 'Application'
  sourceRepos: 
    - 'https://github.com/sprint-cloud/sprint-apps'