apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-staging
  source:
    repoURL: 'https://github.com/sprint-cloud/sprint-apps'
    path: 'apps/hello-world/overlay/staging'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true